server:
  port: 8108

spring:
  profiles:
    active: local
  application:
    name: concert
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 한다.
    url: jdbc:mysql://localhost:3306/concert?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql에 생성한 사용자 계정 정보를 써야 한다.
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379





logging:
  level:
    org.springframework.boot.autoconfigure.logging: ERROR
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.servlet: ERROR
    com.zaxxer.hikari: ERROR
    org.hibernate: trace
    org.springframework: ERROR
    org.apache: ERROR
  path: ./logs

