server:
  port: 8108

spring:
  profiles:
    active: local
  application:
    name: concert
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 한다.
    url: jdbc:mysql://localhost:3306/concert?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql에 생성한 사용자 계정 정보를 써야 한다.
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9100 # 카프카 서버 주소
    consumer:
#      group-id: balance-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      auto-create-topics: true



logging:
  level:
    org.springframework.boot.autoconfigure.logging: ERROR
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.servlet: ERROR
    com.zaxxer.hikari: ERROR
    org.hibernate: trace
    org.springframework: ERROR
    org.apache: ERROR
  path: ./logs

